version: '3'

services:
  django_server:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports: 
      - "80:80"
    depends_on:
      - django_server

volumes:
  static:
